"""initial dogs tables

Revision ID: ff039f83cc21
Revises: 
Create Date: 2026-03-04 14:33:43.853236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff039f83cc21'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metricas_etl',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fecha_ejecucion', sa.DateTime(), nullable=True),
    sa.Column('registros_extraidos', sa.Integer(), nullable=False),
    sa.Column('registros_guardados', sa.Integer(), nullable=False),
    sa.Column('registros_fallidos', sa.Integer(), nullable=True),
    sa.Column('tiempo_ejecucion_segundos', sa.Float(), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('mensaje', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metricas_etl_fecha_ejecucion'), 'metricas_etl', ['fecha_ejecucion'], unique=False)
    op.create_table('razas_perros',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('raza', sa.String(length=200), nullable=False),
    sa.Column('vida_min', sa.Integer(), nullable=False),
    sa.Column('vida_max', sa.Integer(), nullable=False),
    sa.Column('vida_promedio', sa.Float(), nullable=False),
    sa.Column('peso_macho_max', sa.Float(), nullable=False),
    sa.Column('peso_hembra_max', sa.Float(), nullable=False),
    sa.Column('peso_promedio', sa.Float(), nullable=False),
    sa.Column('categoria_peso', sa.String(length=50), nullable=True),
    sa.Column('diferencia_sexual_peso', sa.Float(), nullable=True),
    sa.Column('hipoalergenico', sa.Boolean(), nullable=True),
    sa.Column('fecha_extraccion', sa.DateTime(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_raza_fecha', 'razas_perros', ['raza', 'fecha_extraccion'], unique=False)
    op.create_index(op.f('ix_razas_perros_fecha_extraccion'), 'razas_perros', ['fecha_extraccion'], unique=False)
    op.create_index(op.f('ix_razas_perros_raza'), 'razas_perros', ['raza'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_razas_perros_raza'), table_name='razas_perros')
    op.drop_index(op.f('ix_razas_perros_fecha_extraccion'), table_name='razas_perros')
    op.drop_index('idx_raza_fecha', table_name='razas_perros')
    op.drop_table('razas_perros')
    op.drop_index(op.f('ix_metricas_etl_fecha_ejecucion'), table_name='metricas_etl')
    op.drop_table('metricas_etl')
    # ### end Alembic commands ###
